//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Detalles
    {
        public int ID_Detalles { get; set; }
        public Nullable<int> ID_Entrada { get; set; }
        public Nullable<int> ID_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio_Compra { get; set; }
        public Nullable<int> ID_Sucursal { get; set; }
    
        public virtual Compra_Entrada Compra_Entrada { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
