
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Vendedor
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Vendedor()
    {

        this.Venta_Factura = new HashSet<Venta_Factura>();

    }


    public int ID_Vendedor { get; set; }

    public Nullable<int> ID_Rol { get; set; }

    public string Nombre { get; set; }

    public string Cedula { get; set; }

    public Nullable<System.DateTime> Edad { get; set; }

    public string Usuario { get; set; }

    public string contra { get; set; }

    public string Email { get; set; }

    public Nullable<int> ID_Sucursal { get; set; }

    public Nullable<int> Estado { get; set; }



    public virtual Rol Rol { get; set; }

    public virtual Sucursal Sucursal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Venta_Factura> Venta_Factura { get; set; }

}

}
