
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Venta_Factura
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Venta_Factura()
    {

        this.Venta_Detalles = new HashSet<Venta_Detalles>();

    }


    public int ID_Venta { get; set; }

    public Nullable<int> Estado { get; set; }

    public Nullable<int> ID_Producto { get; set; }

    public Nullable<int> ID_Cliente { get; set; }

    public Nullable<int> ID_Vendedor { get; set; }

    public Nullable<int> ID_Sucursal { get; set; }

    public Nullable<System.DateTime> Fecha_Venta { get; set; }

    public Nullable<int> Cantidad { get; set; }

    public Nullable<decimal> Subtotal { get; set; }

    public Nullable<decimal> Total { get; set; }

    public Nullable<decimal> PrecioProducto { get; set; }

    public Nullable<decimal> Paga { get; set; }

    public Nullable<decimal> Cambio { get; set; }



    public virtual Cliente Cliente { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Sucursal Sucursal { get; set; }

    public virtual Vendedor Vendedor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Venta_Detalles> Venta_Detalles { get; set; }

}

}
