
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Venta_Detalles
{

    public int ID_Detalles { get; set; }

    public Nullable<int> ID_Producto { get; set; }

    public Nullable<int> ID_Venta { get; set; }

    public Nullable<int> Cantidad { get; set; }

    public Nullable<decimal> PrecioProducto { get; set; }



    public virtual Producto Producto { get; set; }

    public virtual Venta_Factura Venta_Factura { get; set; }

}

}
